//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camalot.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Camalot.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not allowed..
        /// </summary>
        public static string AntiForgeryToken_InvalidMethod {
            get {
                return ResourceManager.GetString("AntiForgeryToken_InvalidMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required anti-forgery token was not supplied or was invalid..
        /// </summary>
        public static string AntiForgeryToken_ValidationFailed {
            get {
                return ResourceManager.GetString("AntiForgeryToken_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected html color string format..
        /// </summary>
        public static string Color_UnexpectedFormat {
            get {
                return ResourceManager.GetString("Color_UnexpectedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a day ago.
        /// </summary>
        public static string Date_Friendly1Day {
            get {
                return ResourceManager.GetString("Date_Friendly1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string Date_Friendly1Hour {
            get {
                return ResourceManager.GetString("Date_Friendly1Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string Date_Friendly1Minute {
            get {
                return ResourceManager.GetString("Date_Friendly1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a month ago.
        /// </summary>
        public static string Date_Friendly1Month {
            get {
                return ResourceManager.GetString("Date_Friendly1Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a week ago.
        /// </summary>
        public static string Date_Friendly1Week {
            get {
                return ResourceManager.GetString("Date_Friendly1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a year ago.
        /// </summary>
        public static string Date_Friendly1Year {
            get {
                return ResourceManager.GetString("Date_Friendly1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        public static string Date_FriendlyDay_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyDay_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string Date_FriendlyDays {
            get {
                return ResourceManager.GetString("Date_FriendlyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string Date_FriendlyHour_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyHour_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string Date_FriendlyHours {
            get {
                return ResourceManager.GetString("Date_FriendlyHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Date_FriendlyMinute_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyMinute_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string Date_FriendlyMinutes {
            get {
                return ResourceManager.GetString("Date_FriendlyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string Date_FriendlyMonth_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyMonth_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string Date_FriendlyMonths {
            get {
                return ResourceManager.GetString("Date_FriendlyMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string Date_FriendlyNow {
            get {
                return ResourceManager.GetString("Date_FriendlyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to now.
        /// </summary>
        public static string Date_FriendlyNow_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyNow_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w.
        /// </summary>
        public static string Date_FriendlyWeek_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyWeek_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        public static string Date_FriendlyWeeks {
            get {
                return ResourceManager.GetString("Date_FriendlyWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string Date_FriendlyYear_Short {
            get {
                return ResourceManager.GetString("Date_FriendlyYear_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string Date_FriendlyYears {
            get {
                return ResourceManager.GetString("Date_FriendlyYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not valid for a jsonp callback identifier..
        /// </summary>
        public static string JsonP_InvalidIdentifier {
            get {
                return ResourceManager.GetString("JsonP_InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{2}&apos; must be a value between {0} and {1}..
        /// </summary>
        public static string Require_Between {
            get {
                return ResourceManager.GetString("Require_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; must zero..
        /// </summary>
        public static string Require_Zero {
            get {
                return ResourceManager.GetString("Require_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Xml Node Type.
        /// </summary>
        public static string XmlNode_UnknownNodeType {
            get {
                return ResourceManager.GetString("XmlNode_UnknownNodeType", resourceCulture);
            }
        }
    }
}
